apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: victorferreira/api:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: API_PORT
          value: "3000"
        - name: DB
          value: "postgres://stoned:r0r0llingSt0ne@deploymentLb"
