apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops
  namespace: devops
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: devops
  resources:
    requests:
      storage: 30Gi
